version: "3"
services:

  pity_mysql:
    image: mysql:8.0
    container_name: pity_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Pitytester666666
      MYSQL_DATABASE: pity
      TZ: Asia/Shanghai
    networks:
      pity_net:
        aliases:
          - pity_mysql

  pity_redis:
    image: redis
    container_name: pity_redis
    command: redis-server --requirepass 123456
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      pity_net:
        aliases:
          - pity_redis

  pity:
    build:
      context: ../
      dockerfile: ops/dockerfile
      args:
        buildno: 1
    container_name: pity_server
    ports:
      - "7777:7777"
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      pity_net:
        aliases:
        - pity_server
    volumes:
      - ./dev.env.ops:/pity/conf/dev.env
    command: bash -c '/pity/ops/wait-for-it.sh pity_mysql:3306 -- /pity/ops/wait-for-it.sh pity_redis:6379 -- /pity/venv/bin/supervisord -c /pity/ops/supervisor.conf'


  user:
    build:
      context: ../
      dockerfile: app/v1/service/user/dockerfile
    container_name: pity_user
    ports:
      - "10011:10011"
    restart: always
    networks:
      pity_net:
        aliases:
        - pity_user
    command: bash -c '/pityUser/ops/wait-for-it.sh pity_mysql:3306 && /pityUser/ops/wait-for-it.sh pity_redis:6379 && cd /pityUser/app/v1/service/user && /pityUser/venv/bin/python server.py'


networks:
  pity_net:
